apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  MH_ADDR: "192.168.137.100"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "sample"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-app
  labels:
    app: healthcheck-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheck-test
  template:
    metadata:
      labels:
        app: healthcheck-test
    spec:
      containers:
        - name: health-check-app
          image: chulm/health-check-app:latest
          envFrom:
            - configMapRef:
                name: database-config
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8080


