apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-app
  labels:
    app: healthcheck-test
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcheck-test
  template: ### template 아래는 pod 리소스 정의와 같음.
    metadata:
      labels:
        app: healthcheck-test
    spec:
      containers:
        - name: health-check-app
          image: chulm/health-check-app:latest
#          image: gihyodocker/ech:patched
          ports:
            - containerPort: 8080

