kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: "system:anonymous"
    namespace: default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-clusterrole
  apiGroup: rbac.authorization.k8s.io

