kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-rolebinding
  namespace: default
subjects: # 어떤 유형의 user와 연결할지
  - kind: ServiceAccount
    name: myuser
    apiGroup: ""
roleRef:  #기존의 만들었던 role 참조
  kind: Role
  name: read-role
  apiGroup: rbac.authorization.k8s.io
